import os
import io
import sys
import json
import logging
import google.generativeai as genai

# Import all 5 Quantitative Agents
from fundamental_agent import FundamentalAgent
from sentiment_agent import SentimentAgent
from technical_agent import TechnicalAgent
from fetch_ai_agent import FetchAIAgentConnector
from insider_agent import InsiderIntegrityAuditor

# Robust logging format for agent connection interactions
logging.basicConfig(level=logging.INFO, format='[SUPERVISOR] %(message)s')

class SupervisorAgent:
    def __init__(self):
        self.google_api_key = os.getenv("GEMINI_API_KEY")
        if self.google_api_key:
            genai.configure(api_key=self.google_api_key)
            # Use gemini-2.5-flash for speed and complex data structuring
            self.model = genai.GenerativeModel('gemini-2.5-flash')
        else:
            self.model = None
            
        # Explicit instructions to force the LLM to output ONLY the requested Markdown table
        self.table_prompt = """
        You are the 'Supervisor Agent' for the Quant Desk.
        Your directive is to analyze the appended raw textual reports generated by your 5 subordinate agents.
        
        For EACH agent, you must deduce their ultimate directional bias (Buy, Sell, or Neutral).
        You must also deduce a quantitative Confidence Score (0-100) based on the strength and conviction of their specialized report.
        
        Output the final aggregation STRICTLY as a Markdown table with exactly these 3 columns:
        | Agent | Signal | Score |
        |---|---|---|
        | Fundamental Agent | ... | ... |
        | Sentiment Agent | ... | ... |
        | Technical Agent | ... | ... |
        | Insider Agent | ... | ... |
        | Fetch.AI Agent | ... | ... |
        
        Do not provide conversational filler. Only the table.
        """

    def extract_ticker(self, user_prompt):
        """Uses Natural Language Processing to extract just the stock ticker from a human query."""
        if not self.model: return "AAPL" # Fallback
        
        try:
            prompt = f"Extract ONLY the 1-5 letter stock ticker symbol from this text. Return the uppercase string. If you cannot find one, return AAPL.\n\nText: {user_prompt}"
            response = self.model.generate_content(prompt)
            return response.text.strip().upper()
        except Exception as e:
            logging.error(f"NLP Ticker Extraction Error: {e}")
            return "AAPL"

    def execute(self, natural_language_request):
        logging.info("Activating... Parsing natural language request.")
        ticker = self.extract_ticker(natural_language_request)
        logging.info(f"Target Ticker identified: {ticker}")
        
        reports = {}

        # 1. Fundamental Agent Query
        try:
            logging.info("Querying Fundamental Agent...")
            reports['Fundamental'] = FundamentalAgent(ticker).review()
        except Exception as e:
            logging.error(f"Fundamental connection failed: {e}")
            reports['Fundamental'] = f"CONNECTION ERROR: {e}"

        # 2. Sentiment Agent Query
        try:
            logging.info("Querying Sentiment Agent...")
            reports['Sentiment'] = SentimentAgent(ticker).review()
        except Exception as e:
            logging.error(f"Sentiment connection failed: {e}")
            reports['Sentiment'] = f"CONNECTION ERROR: {e}"

        # 3. Technical Agent Query
        try:
            logging.info("Querying Technical Agent...")
            reports['Technical'] = TechnicalAgent(ticker).review()
        except Exception as e:
            logging.error(f"Technical connection failed: {e}")
            reports['Technical'] = f"CONNECTION ERROR: {e}"

        # 4. Fetch.AI Agent Query
        try:
            logging.info("Querying Fetch.AI Agent...")
            connector = FetchAIAgentConnector()
            reports['Fetch.AI'] = connector.dispatch_task(ticker, "Supervisor request for raw macro consensus.")
        except Exception as e:
            logging.error(f"Fetch.AI connection failed: {e}")
            reports['Fetch.AI'] = f"CONNECTION ERROR: {e}"

        # 5. Insider Agent Query
        try:
            logging.info("Querying Insider Agent (Orchestrator)...")
            # Force the candidate list to target only the requested ticker safely
            with open("candidates.json", "w") as f:
                json.dump({"tickers": [ticker]}, f)
                
            # Intercept print-to-stdout payload generated by InsiderIntegrityAuditor's run_audit()
            captured_output = io.StringIO()
            sys.stdout = captured_output
            
            auditor = InsiderIntegrityAuditor()
            auditor.run_audit()
            
            sys.stdout = sys.__stdout__ # Restore standard output
            reports['Insider'] = captured_output.getvalue()
        except Exception as e:
            sys.stdout = sys.__stdout__ # Ensure safety
            logging.error(f"Insider Agent connection failed: {e}")
            reports['Insider'] = f"CONNECTION ERROR: {e}"

        logging.info("All agents successfully queried. Synthesizing final Supervisor Table...")
        
        if not self.model:
            return "[!] OVERRIDE ERROR: GEMINI_API_KEY environment variable is missing. Cannot synthesize table limits."
            
        combined_payload = "\n\n".join([f"--- {name.upper()} AGENT REPORT ---\n{text}" for name, text in reports.items()])
        
        try:
            prompt = f"{self.table_prompt}\n\nHere is the raw data collected for {ticker}:\n{combined_payload}"
            response = self.model.generate_content(prompt)
            return f"\n### 📊 SUPERVISOR DESK REPORT: {ticker}\n\n" + response.text
        except Exception as e:
            return f"[!] Supervisor Gemini Aggregation Error: {e}"

if __name__ == "__main__":
    supervisor = SupervisorAgent()
    # Example natural language execution
    prompt = "I've been hearing a lot of hype about Tesla cars recently. Can you check if the stock is a buy right now?"
    print(f"\nUser Query: '{prompt}'")
    print(supervisor.execute(prompt))
